spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
message:
  response: Hello springboot from dev

kafka.broker: localhost:9092,localhost:9093,localhost:9094
enable.auto.commit: true
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: my-topic

---
spring:
  profiles: stage
message:
  response: Hello springboot from stage

---
spring:
  profiles: prod
message:
  response: Hello springboot from prod

---
